# Generated by Django 5.0.6 on 2024-05-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_project', models.CharField(max_length=100)),
                ('tujuan_project', models.CharField(max_length=1000)),
                ('tangmul_project', models.DateField()),
                ('tangsel_project', models.DateField()),
                ('pic_project', models.CharField(max_length=40)),
                ('status_project', models.TextField()),
            ],
        ),
    ]
