# Generated by Django 5.0.6 on 2024-05-16 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='tanggal_add',
            field=models.DateField(auto_now=True),
        ),
    ]
