# Generated by Django 5.0.6 on 2024-05-30 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de', '0002_projectinfo_tanggal_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anggota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ang', models.CharField(max_length=40)),
                ('tangla_ang', models.DateField()),
                ('deskom_ang', models.CharField(max_length=1000)),
                ('deskpen_ang', models.CharField(max_length=1000)),
                ('peran_ang', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='de.projectinfo')),
            ],
        ),
    ]
