# Generated by Django 5.0.6 on 2024-06-12 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de', '0003_anggota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggota',
            name='author',
        ),
        migrations.AddField(
            model_name='anggota',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='de.projectinfo'),
        ),
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pek', models.CharField(max_length=40)),
                ('desk_pek', models.CharField(max_length=1000)),
                ('tangmul_pek', models.DateField()),
                ('tempatmul_pek', models.CharField(max_length=1000)),
                ('tangsel_pek', models.DateField()),
                ('tempatsel_pek', models.CharField(max_length=1000)),
                ('pel_pek', models.CharField(max_length=1000)),
                ('super_pek', models.CharField(max_length=50)),
                ('status_pek', models.TextField()),
                ('project', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pekerjaan', to='de.projectinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Aktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_akti', models.CharField(max_length=50)),
                ('wakpel_akti', models.DateField()),
                ('pel_akti', models.CharField(max_length=1000)),
                ('eval_akti', models.CharField(max_length=1000)),
                ('ren_akti', models.CharField(max_length=1000)),
                ('status_pek', models.TextField()),
                ('pekerjaan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aktivitas', to='de.pekerjaan')),
            ],
        ),
    ]
