# Generated by Django 5.0.6 on 2024-06-20 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('de', '0005_alter_pekerjaan_tangsel_pek_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anggota',
        ),
    ]
