# Generated by Django 5.0.6 on 2024-06-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('de', '0006_delete_anggota'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktivitas',
            name='biaya_ak',
            field=models.IntegerField(default=0.0, max_length=12),
        ),
        migrations.AddField(
            model_name='pekerjaan',
            name='biaya_pek',
            field=models.IntegerField(blank=True, default=0.0, max_length=12),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='biaya',
            field=models.IntegerField(blank=True, default=0.0, max_length=12),
        ),
    ]
