# Generated by Django 5.0.6 on 2024-07-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('de', '0010_projectinfo_is_archived_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aktivitas',
            old_name='biaya_ak',
            new_name='biaya_akti',
        ),
        migrations.RenameField(
            model_name='aktivitas',
            old_name='status_pek',
            new_name='status_akti',
        ),
    ]
